services:
  neo4j_etl:
    build:
      context: /noe4j_etl
    env_file:
      - .env

  chatbot_api:
    build:
      context: /chatbot_api
    env_file:
      - .env
    depends_on:
      - neo4j_etl
    ports:
      - "8000:8000"

  chatbot_frontend:
    build:
      context: ./chatbot_frontend
    env_file:
      - .env
    depends_on:
      - chatbot_api
    ports:
      - "8501:8501"

  extract_transform_data:
    build:
      context: ./extract_transform
    env_file:
      - .env
    volumes:
      - ./coletor_data:/coletor_data