[project]
name = "chatbot_frontend"
version = "0.1"
dependencies = [
   "requests==2.31.0",
   "streamlit==1.29.0",
   "websockets>=12.0",
   "streamlit-autorefresh==1.0.1"
]

[project.optional-dependencies]
dev = ["black", "flake8"]
